# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Patrol Field Effort
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    view_state_from_geodataframes as view_state_from_geodataframes,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    assert_polygon_types as assert_polygon_types,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import spatial_join as spatial_join
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    to_quantity as to_quantity,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_bin_colors as add_bin_colors,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_index_column as add_index_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_non_null_flag as add_non_null_flag,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_time_since_visit as add_time_since_visit,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_visit_bins as add_visit_bins,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    compute_dwell_time as compute_dwell_time,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    compute_patrol_effort_fraction as compute_patrol_effort_fraction,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    hex_column_to_rgba as hex_column_to_rgba,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    operational_days as operational_days,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    order_bin_categories as order_bin_categories,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    overlay_gdf as overlay_gdf,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    reset_df_index as reset_df_index,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    set_spatial_features_opacity as set_spatial_features_opacity,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_linear_time_density as calculate_linear_time_density,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    create_meshgrid as create_meshgrid,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrol_observations as get_patrol_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Set groupers

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S", **time_range_params)
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps_pydeck.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ## Area of Interest

# %%
# parameters

select_geo_er_params = dict(
    source=...,
    group_by=...,
)

# %%
# call the task


select_geo_er = (
    get_spatial_features.set_task_instance_id("select_geo_er")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(client=er_client_name, legend_title="Legend", **select_geo_er_params)
    .call()
)


# %% [markdown]
# ## Fetch Patrol Observations

# %%
# parameters

get_patrol_obs_params = dict(
    patrol_types=...,
)

# %%
# call the task


get_patrol_obs = (
    get_patrol_observations.set_task_instance_id("get_patrol_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        status=["done"],
        include_patrol_details=True,
        raise_on_empty=True,
        sub_page_size=100,
        patrols_overlap_daterange=True,
        **get_patrol_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Build Patrol Trajectories

# %%
# parameters

patrol_obs_trajs_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


patrol_obs_trajs = (
    relocations_to_trajectory.set_task_instance_id("patrol_obs_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocations=get_patrol_obs, **patrol_obs_trajs_params)
    .call()
)


# %% [markdown]
# ## Validate Study Area Geometry

# %%
# parameters

assert_polygon_params = dict()

# %%
# call the task


assert_polygon = (
    assert_polygon_types.set_task_instance_id("assert_polygon")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=select_geo_er, **assert_polygon_params)
    .call()
)


# %% [markdown]
# ## Prepare Study Area for Analysis

# %%
# parameters

reproject_spatial_3857_params = dict()

# %%
# call the task


reproject_spatial_3857 = (
    reproject_gdf.set_task_instance_id("reproject_spatial_3857")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=select_geo_er, target_crs="EPSG:3857", **reproject_spatial_3857_params)
    .call()
)


# %% [markdown]
# ## Save Study Area to File

# %%
# parameters

persist_spatial_file_params = dict()

# %%
# call the task


persist_spatial_file = (
    persist_df_wrapper.set_task_instance_id("persist_spatial_file")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=reproject_spatial_3857,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename="spatial_file",
        filetypes=["gpkg"],
        filename_prefix="er_spatial_file",
        sanitize=False,
        **persist_spatial_file_params,
    )
    .call()
)


# %% [markdown]
# ## Create Analysis Grid

# %%
# parameters

create_geo_meshgrid_params = dict(
    auto_scale_or_custom_cell_size=...,
)

# %%
# call the task


create_geo_meshgrid = (
    create_meshgrid.set_task_instance_id("create_geo_meshgrid")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        aoi=reproject_spatial_3857,
        crs="EPSG:3857",
        intersecting_only=True,
        **create_geo_meshgrid_params,
    )
    .call()
)


# %% [markdown]
# ## Clip Grid to Study Area

# %%
# parameters

overlay_meshgrid_spatial_params = dict()

# %%
# call the task


overlay_meshgrid_spatial = (
    overlay_gdf.set_task_instance_id("overlay_meshgrid_spatial")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        left=create_geo_meshgrid,
        right=reproject_spatial_3857,
        how="intersection",
        keep_geom_type=True,
        make_valid=True,
        **overlay_meshgrid_spatial_params,
    )
    .call()
)


# %% [markdown]
# ## Index Grid Cells

# %%
# parameters

meshgrid_idx_id_params = dict()

# %%
# call the task


meshgrid_idx_id = (
    add_index_column.set_task_instance_id("meshgrid_idx_id")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=overlay_meshgrid_spatial, column="cell_id", **meshgrid_idx_id_params)
    .call()
)


# %% [markdown]
# ## Prepare Patrol Trajectories for Analysis

# %%
# parameters

reproject_trajs_params = dict()

# %%
# call the task


reproject_trajs = (
    reproject_gdf.set_task_instance_id("reproject_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=patrol_obs_trajs, target_crs="EPSG:3857", **reproject_trajs_params)
    .call()
)


# %% [markdown]
# ## Select Trajectory Columns

# %%
# parameters

select_patrol_columns_params = dict()

# %%
# call the task


select_patrol_columns = (
    select_columns.set_task_instance_id("select_patrol_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=reproject_trajs,
        columns=["segment_start", "segment_end", "geometry"],
        raise_on_missing=True,
        **select_patrol_columns_params,
    )
    .call()
)


# %% [markdown]
# ## Overlay Patrols on Grid

# %%
# parameters

spatial_join_patrol_trajs_params = dict()

# %%
# call the task


spatial_join_patrol_trajs = (
    spatial_join.set_task_instance_id("spatial_join_patrol_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        left_df=select_patrol_columns,
        right_df=meshgrid_idx_id,
        how="inner",
        predicate="intersects",
        **spatial_join_patrol_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize Patrol Visits per Grid Cell

# %%
# parameters

summarize_df_grids_params = dict()

# %%
# call the task


summarize_df_grids = (
    summarize_df.set_task_instance_id("summarize_df_grids")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=spatial_join_patrol_trajs,
        groupby_cols=["cell_id"],
        reset_index=True,
        summary_params=[
            {
                "display_name": "last_visited",
                "aggregator": "max",
                "column": "segment_end",
                "original_unit": None,
                "new_unit": None,
                "decimal_places": None,
            },
            {
                "display_name": "first_visited",
                "aggregator": "min",
                "column": "segment_start",
                "original_unit": None,
                "new_unit": None,
                "decimal_places": None,
            },
        ],
        **summarize_df_grids_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate Days Since Last Visit

# %%
# parameters

add_time_params = dict()

# %%
# call the task


add_time = (
    add_time_since_visit.set_task_instance_id("add_time")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=summarize_df_grids, time_range=time_range, **add_time_params)
    .call()
)


# %% [markdown]
# ## Attach Visit Stats to Grid

# %%
# parameters

merge_gridded_stats_params = dict()

# %%
# call the task


merge_gridded_stats = (
    merge_two_dataframes.set_task_instance_id("merge_gridded_stats")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        left=meshgrid_idx_id,
        right=add_time,
        how="left",
        on="cell_id",
        left_on=None,
        right_on=None,
        left_index=False,
        right_index=False,
        fillna_value=None,
        **merge_gridded_stats_params,
    )
    .call()
)


# %% [markdown]
# ## Flag Visited Cells (Days Since Visit)

# %%
# parameters

add_null_flag_params = dict()

# %%
# call the task


add_null_flag = (
    add_non_null_flag.set_task_instance_id("add_null_flag")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=merge_gridded_stats,
        source_column="days_since_visit",
        flag_column="visited",
        **add_null_flag_params,
    )
    .call()
)


# %% [markdown]
# ## Classify Days Since Visit into Bins

# %%
# parameters

add_custom_visit_bins_params = dict()

# %%
# call the task


add_custom_visit_bins = (
    add_visit_bins.set_task_instance_id("add_custom_visit_bins")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_null_flag,
        col="days_since_visit",
        visited_col="visited",
        new_col="visit_bin",
        bins=5,
        scheme="natural_breaks",
        **add_custom_visit_bins_params,
    )
    .call()
)


# %% [markdown]
# ## Color Days Since Visit Bins

# %%
# parameters

add_visit_bin_colors_params = dict()

# %%
# call the task


add_visit_bin_colors = (
    add_bin_colors.set_task_instance_id("add_visit_bin_colors")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_custom_visit_bins,
        col="visit_bin",
        new_col="hex_color",
        cmap={"type_": "palette", "name": "RdYlGn_r"},
        unvisited="#808080",
        **add_visit_bin_colors_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare Visit Layer for Mapping

# %%
# parameters

reproject_4326_params = dict()

# %%
# call the task


reproject_4326 = (
    reproject_gdf.set_task_instance_id("reproject_4326")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=add_visit_bin_colors, target_crs="EPSG:4326", **reproject_4326_params)
    .call()
)


# %% [markdown]
# ## Save Days Since Visit Data

# %%
# parameters

persist_visit_params = dict()

# %%
# call the task


persist_visit = (
    persist_df_wrapper.set_task_instance_id("persist_visit")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=reproject_4326,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename=None,
        filetypes=["gpkg"],
        filename_prefix="days_since_patrol_visit",
        sanitize=False,
        **persist_visit_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare Trajectories for Dwell Calculation

# %%
# parameters

reset_patrol_trajs_params = dict()

# %%
# call the task


reset_patrol_trajs = (
    reset_df_index.set_task_instance_id("reset_patrol_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=reproject_trajs, drop=False, **reset_patrol_trajs_params)
    .call()
)


# %% [markdown]
# ## Calculate Time Spent per Grid Cell

# %%
# parameters

compute_patrol_dwell_params = dict()

# %%
# call the task


compute_patrol_dwell = (
    compute_dwell_time.set_task_instance_id("compute_patrol_dwell")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        patrol_trajectories=reset_patrol_trajs,
        gridded_spatial_feature=meshgrid_idx_id,
        **compute_patrol_dwell_params,
    )
    .call()
)


# %% [markdown]
# ## Attach Dwell Time to Grid

# %%
# parameters

merge_dwell_gdf_params = dict()

# %%
# call the task


merge_dwell_gdf = (
    merge_two_dataframes.set_task_instance_id("merge_dwell_gdf")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        left=meshgrid_idx_id,
        right=compute_patrol_dwell,
        how="left",
        on="cell_id",
        left_on=None,
        right_on=None,
        left_index=False,
        right_index=False,
        fillna_value=None,
        **merge_dwell_gdf_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare Dwell Layer for Mapping

# %%
# parameters

reproject_dwell_gdf_params = dict()

# %%
# call the task


reproject_dwell_gdf = (
    reproject_gdf.set_task_instance_id("reproject_dwell_gdf")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=merge_dwell_gdf, target_crs="EPSG:4326", **reproject_dwell_gdf_params)
    .call()
)


# %% [markdown]
# ## Flag Visited Cells (Dwell Time)

# %%
# parameters

add_null_dwell_flag_params = dict()

# %%
# call the task


add_null_dwell_flag = (
    add_non_null_flag.set_task_instance_id("add_null_dwell_flag")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=reproject_dwell_gdf,
        source_column="hours_in_cell",
        flag_column="visited",
        **add_null_dwell_flag_params,
    )
    .call()
)


# %% [markdown]
# ## Classify Dwell Time into Bins

# %%
# parameters

add_custom_dwell_bins_params = dict()

# %%
# call the task


add_custom_dwell_bins = (
    add_visit_bins.set_task_instance_id("add_custom_dwell_bins")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_null_dwell_flag,
        col="hours_in_cell",
        visited_col="visited",
        new_col="visit_bin",
        bins=5,
        scheme="natural_breaks",
        **add_custom_dwell_bins_params,
    )
    .call()
)


# %% [markdown]
# ## Color Dwell Time Bins

# %%
# parameters

add_dwell_bin_colors_params = dict()

# %%
# call the task


add_dwell_bin_colors = (
    add_bin_colors.set_task_instance_id("add_dwell_bin_colors")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_custom_dwell_bins,
        col="visit_bin",
        new_col="hex_color",
        cmap={"type_": "palette", "name": "RdYlGn"},
        unvisited="#808080",
        **add_dwell_bin_colors_params,
    )
    .call()
)


# %% [markdown]
# ## Save Dwell Time Data

# %%
# parameters

persist_dwell_gkpg_params = dict()

# %%
# call the task


persist_dwell_gkpg = (
    persist_df_wrapper.set_task_instance_id("persist_dwell_gkpg")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_dwell_bin_colors,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename=None,
        filetypes=["gpkg"],
        filename_prefix="time_spent_per_cell",
        sanitize=False,
        **persist_dwell_gkpg_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate Patrol Route Density

# %%
# parameters

calc_ltd_aoi_params = dict()

# %%
# call the task


calc_ltd_aoi = (
    calculate_linear_time_density.set_task_instance_id("calc_ltd_aoi")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        percentiles=None,
        trajectory_gdf=reproject_trajs,
        meshgrid=overlay_meshgrid_spatial,
        **calc_ltd_aoi_params,
    )
    .call()
)


# %% [markdown]
# ## Save Route Density Data

# %%
# parameters

persist_ltd_gkpg_params = dict()

# %%
# call the task


persist_ltd_gkpg = (
    persist_df_wrapper.set_task_instance_id("persist_ltd_gkpg")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=calc_ltd_aoi,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename=None,
        filetypes=["gpkg"],
        filename_prefix="patrols_linear_time_density",
        sanitize=False,
        **persist_ltd_gkpg_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare Route Density for Mapping

# %%
# parameters

reproject_ltd_params = dict()

# %%
# call the task


reproject_ltd = (
    reproject_gdf.set_task_instance_id("reproject_ltd")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=calc_ltd_aoi, target_crs="EPSG:4326", **reproject_ltd_params)
    .call()
)


# %% [markdown]
# ## Flag Cells with Patrol Coverage

# %%
# parameters

add_null_ltd_flag_params = dict()

# %%
# call the task


add_null_ltd_flag = (
    add_non_null_flag.set_task_instance_id("add_null_ltd_flag")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=reproject_ltd,
        source_column="percentile",
        flag_column="visited",
        **add_null_ltd_flag_params,
    )
    .call()
)


# %% [markdown]
# ## Classify Route Density into Bins

# %%
# parameters

add_custom_ltd_bins_params = dict()

# %%
# call the task


add_custom_ltd_bins = (
    add_visit_bins.set_task_instance_id("add_custom_ltd_bins")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_null_ltd_flag,
        col="percentile",
        visited_col="visited",
        new_col="visit_bin",
        bins=5,
        scheme="natural_breaks",
        **add_custom_ltd_bins_params,
    )
    .call()
)


# %% [markdown]
# ## Color Route Density Bins

# %%
# parameters

add_ltd_bin_colors_params = dict()

# %%
# call the task


add_ltd_bin_colors = (
    add_bin_colors.set_task_instance_id("add_ltd_bin_colors")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_custom_ltd_bins,
        col="visit_bin",
        new_col="hex_color",
        cmap={"type_": "palette", "name": "RdYlGn"},
        unvisited="#808080",
        **add_ltd_bin_colors_params,
    )
    .call()
)


# %% [markdown]
# ## Standardize Patrol Column Names

# %%
# parameters

rename_patrol_cols_params = dict()

# %%
# call the task


rename_patrol_cols = (
    map_columns.set_task_instance_id("rename_patrol_cols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        df=reproject_trajs,
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "extra__patrol_type__value": "patrol_type",
            "extra__patrol_serial_number": "patrol_serial_number",
            "extra__patrol_status": "patrol_status",
            "extra__patrol_subject": "Name",
            "extra__subject_id": "ID",
        },
        **rename_patrol_cols_params,
    )
    .call()
)


# %% [markdown]
# ## Generate operational days summary table

# %%
# parameters

op_summary_table_params = dict()

# %%
# call the task


op_summary_table = (
    operational_days.set_task_instance_id("op_summary_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        trajs=rename_patrol_cols,
        segment_start="segment_start",
        segment_end="segment_end",
        groupby_cols=["ID", "Name"],
        **op_summary_table_params,
    )
    .call()
)


# %% [markdown]
# ## Save Operational Days Table (CSV)

# %%
# parameters

persist_oper_table_params = dict()

# %%
# call the task


persist_oper_table = (
    persist_df_wrapper.set_task_instance_id("persist_oper_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=op_summary_table,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename=None,
        filetypes=["csv"],
        filename_prefix="patrol_operational_days",
        sanitize=False,
        **persist_oper_table_params,
    )
    .call()
)


# %% [markdown]
# ## Save Patrol Observations

# %%
# parameters

persist_patrol_obs_params = dict()

# %%
# call the task


persist_patrol_obs = (
    persist_df_wrapper.set_task_instance_id("persist_patrol_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=get_patrol_obs,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename=None,
        filetypes=["gpkg"],
        filename_prefix="patrol_observations",
        sanitize=False,
        **persist_patrol_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Save Patrol Trajectories

# %%
# parameters

persist_patrol_trajs_params = dict()

# %%
# call the task


persist_patrol_trajs = (
    persist_df_wrapper.set_task_instance_id("persist_patrol_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_obs_trajs,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename=None,
        filetypes=["gpkg"],
        filename_prefix="patrol_trajectories",
        sanitize=False,
        **persist_patrol_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Set Study Area Opacity

# %%
# parameters

spatial_features_opacity_params = dict()

# %%
# call the task


spatial_features_opacity = (
    set_spatial_features_opacity.set_task_instance_id("spatial_features_opacity")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=select_geo_er,
        fill_opacity=0.0,
        line_opacity=1.0,
        **spatial_features_opacity_params,
    )
    .call()
)


# %% [markdown]
# ## Build Study Area Map Layer

# %%
# parameters

spatial_features_layer_params = dict()

# %%
# call the task


spatial_features_layer = (
    create_spatial_features_layer.set_task_instance_id("spatial_features_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(geodataframe=spatial_features_opacity, **spatial_features_layer_params)
    .call()
)


# %% [markdown]
# ## Calculate Map Zoom and Position

# %%
# parameters

overall_zoom_value_params = dict()

# %%
# call the task


overall_zoom_value = (
    view_state_from_geodataframes.set_task_instance_id("overall_zoom_value")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(geodataframes=[select_geo_er], max_zoom=15, **overall_zoom_value_params)
    .call()
)


# %% [markdown]
# ## Prepare Colors for Days Since Visit Map

# %%
# parameters

add_time_visit_rgba_params = dict()

# %%
# call the task


add_time_visit_rgba = (
    hex_column_to_rgba.set_task_instance_id("add_time_visit_rgba")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=reproject_4326,
        column="hex_color",
        new_column="rgba_color",
        **add_time_visit_rgba_params,
    )
    .call()
)


# %% [markdown]
# ## Sort Days Since Visit Legend

# %%
# parameters

order_bin_visit_since_params = dict()

# %%
# call the task


order_bin_visit_since = (
    order_bin_categories.set_task_instance_id("order_bin_visit_since")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_time_visit_rgba, bin_column="visit_bin", **order_bin_visit_since_params
    )
    .call()
)


# %% [markdown]
# ## Build Days Since Visit Map Layer

# %%
# parameters

create_time_since_layer_params = dict()

# %%
# call the task


create_time_since_layer = (
    create_geojson_layer.set_task_instance_id("create_time_since_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        data_url=None,
        geodataframe=order_bin_visit_since,
        layer_style={
            "filled": True,
            "extruded": False,
            "stroked": True,
            "get_fill_color": "rgba_color",
            "get_line_color": [0, 0, 0],
            "opacity": 0.65,
            "get_line_width": 0.35,
        },
        legend={
            "title": "Time Since Visit (Days)",
            "label_column": "visit_bin",
            "color_column": "rgba_color",
            "sort": "ascending",
            "label_suffix": None,
        },
        **create_time_since_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Render Days Since Visit Map

# %%
# parameters

draw_time_since_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_time_since_map = (
    draw_map.set_task_instance_id("draw_time_since_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        max_zoom=10,
        static=False,
        title=None,
        geo_layers=[create_time_since_layer, spatial_features_layer],
        tile_layers=base_map_defs,
        legend_style={"placement": "bottom-right"},
        view_state=overall_zoom_value,
        **draw_time_since_map_params,
    )
    .call()
)


# %% [markdown]
# ## Save Days Since Visit Map

# %%
# parameters

time_since_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


time_since_urls = (
    persist_text.set_task_instance_id("time_since_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_time_since_map,
        filename="days_since_patrol_visit_map.html",
        **time_since_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare Colors for Dwell Time Map

# %%
# parameters

add_dwell_rgba_params = dict()

# %%
# call the task


add_dwell_rgba = (
    hex_column_to_rgba.set_task_instance_id("add_dwell_rgba")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_dwell_bin_colors,
        column="hex_color",
        new_column="rgba_color",
        **add_dwell_rgba_params,
    )
    .call()
)


# %% [markdown]
# ## Sort Dwell Time Legend

# %%
# parameters

order_bin_dwell_since_params = dict()

# %%
# call the task


order_bin_dwell_since = (
    order_bin_categories.set_task_instance_id("order_bin_dwell_since")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=add_dwell_rgba, bin_column="visit_bin", **order_bin_dwell_since_params)
    .call()
)


# %% [markdown]
# ## Build Dwell Time Map Layer

# %%
# parameters

create_dwell_layer_params = dict()

# %%
# call the task


create_dwell_layer = (
    create_geojson_layer.set_task_instance_id("create_dwell_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        data_url=None,
        geodataframe=order_bin_dwell_since,
        layer_style={
            "filled": True,
            "extruded": False,
            "stroked": True,
            "get_fill_color": "rgba_color",
            "get_line_color": [0, 0, 0],
            "opacity": 0.65,
            "get_line_width": 0.35,
        },
        legend={
            "title": "Time Spent(Hours)",
            "label_column": "visit_bin",
            "color_column": "rgba_color",
            "sort": "ascending",
            "label_suffix": None,
        },
        **create_dwell_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Render Dwell Time Map

# %%
# parameters

draw_dwell_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_dwell_map = (
    draw_map.set_task_instance_id("draw_dwell_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        max_zoom=10,
        static=False,
        title=None,
        geo_layers=[create_dwell_layer, spatial_features_layer],
        tile_layers=base_map_defs,
        legend_style={"placement": "bottom-right"},
        view_state=overall_zoom_value,
        **draw_dwell_map_params,
    )
    .call()
)


# %% [markdown]
# ## Save Dwell Time Map

# %%
# parameters

dwell_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


dwell_urls = (
    persist_text.set_task_instance_id("dwell_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_dwell_map,
        filename="time_spent_per_grid_map.html",
        **dwell_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare Colors for Route Density Map

# %%
# parameters

add_ltd_rgba_params = dict()

# %%
# call the task


add_ltd_rgba = (
    hex_column_to_rgba.set_task_instance_id("add_ltd_rgba")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_ltd_bin_colors,
        column="hex_color",
        new_column="rgba_color",
        **add_ltd_rgba_params,
    )
    .call()
)


# %% [markdown]
# ## Sort Route Density Legend

# %%
# parameters

order_bin_ltd_since_params = dict()

# %%
# call the task


order_bin_ltd_since = (
    order_bin_categories.set_task_instance_id("order_bin_ltd_since")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=add_ltd_rgba, bin_column="visit_bin", **order_bin_ltd_since_params)
    .call()
)


# %% [markdown]
# ## Build Route Density Map Layer

# %%
# parameters

create_ltd_layer_params = dict()

# %%
# call the task


create_ltd_layer = (
    create_geojson_layer.set_task_instance_id("create_ltd_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        data_url=None,
        geodataframe=order_bin_ltd_since,
        layer_style={
            "filled": True,
            "extruded": False,
            "stroked": True,
            "get_fill_color": "rgba_color",
            "get_line_color": [0, 0, 0],
            "opacity": 0.65,
            "get_line_width": 0.35,
        },
        legend={
            "title": "Time Spent",
            "label_column": "visit_bin",
            "color_column": "rgba_color",
            "sort": "ascending",
            "label_suffix": None,
        },
        **create_ltd_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Render Route Density Map

# %%
# parameters

draw_ltd_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_ltd_map = (
    draw_map.set_task_instance_id("draw_ltd_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        max_zoom=10,
        static=False,
        title=None,
        geo_layers=[create_ltd_layer, spatial_features_layer],
        tile_layers=base_map_defs,
        legend_style={"placement": "bottom-right"},
        view_state=overall_zoom_value,
        **draw_ltd_map_params,
    )
    .call()
)


# %% [markdown]
# ## Save Route Density Map

# %%
# parameters

ltd_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


ltd_urls = (
    persist_text.set_task_instance_id("ltd_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_ltd_map,
        filename="ltd_patrols_map.html",
        **ltd_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate total patrols

# %%
# parameters

total_patrols_params = dict()

# %%
# call the task


total_patrols = (
    dataframe_column_nunique.set_task_instance_id("total_patrols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column_name="ID", df=rename_patrol_cols, **total_patrols_params)
    .call()
)


# %% [markdown]
# ## Calculate Total Patrol Distance

# %%
# parameters

total_patrol_dist_params = dict()

# %%
# call the task


total_patrol_dist = (
    dataframe_column_sum.set_task_instance_id("total_patrol_dist")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="dist_meters", df=rename_patrol_cols, **total_patrol_dist_params
    )
    .call()
)


# %% [markdown]
# ## Convert Distance to Kilometres

# %%
# parameters

total_patrol_dist_converted_params = dict()

# %%
# call the task


total_patrol_dist_converted = (
    with_unit.set_task_instance_id("total_patrol_dist_converted")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        original_unit="m",
        new_unit="km",
        value=total_patrol_dist,
        **total_patrol_dist_converted_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate Patrol Coverage Fraction

# %%
# parameters

patrol_effort_spatial_params = dict()

# %%
# call the task


patrol_effort_spatial = (
    compute_patrol_effort_fraction.set_task_instance_id("patrol_effort_spatial")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=add_visit_bin_colors, **patrol_effort_spatial_params)
    .call()
)


# %% [markdown]
# ## Create Total Patrols Widget

# %%
# parameters

total_patrols_sv_widget_params = dict(
    view=...,
)

# %%
# call the task


total_patrols_sv_widget = (
    create_single_value_widget_single_view.set_task_instance_id(
        "total_patrols_sv_widget"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total Patrols",
        decimal_places=0,
        data=total_patrols,
        **total_patrols_sv_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Create Total Distance Widget

# %%
# parameters

total_patrol_dist_sv_widget_params = dict(
    view=...,
)

# %%
# call the task


total_patrol_dist_sv_widget = (
    create_single_value_widget_single_view.set_task_instance_id(
        "total_patrol_dist_sv_widget"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total Patrol Distance",
        decimal_places=1,
        data=total_patrol_dist_converted,
        **total_patrol_dist_sv_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Format Patrol Coverage as Percentage

# %%
# parameters

patrol_effort_quantity_params = dict()

# %%
# call the task


patrol_effort_quantity = (
    to_quantity.set_task_instance_id("patrol_effort_quantity")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(value=patrol_effort_spatial, unit="%", **patrol_effort_quantity_params)
    .call()
)


# %% [markdown]
# ## Create Patrol Coverage Widget

# %%
# parameters

patrol_effort_sv_widget_params = dict(
    view=...,
)

# %%
# call the task


patrol_effort_sv_widget = (
    create_single_value_widget_single_view.set_task_instance_id(
        "patrol_effort_sv_widget"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Patrol Coverage",
        decimal_places=1,
        data=patrol_effort_quantity,
        **patrol_effort_sv_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Create Time Since Visit Map Widget

# %%
# parameters

time_since_map_widget_params = dict(
    view=...,
)

# %%
# call the task


time_since_map_widget = (
    create_map_widget_single_view.set_task_instance_id("time_since_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Days Since Patrol Visit",
        data=time_since_urls,
        **time_since_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dwell Time Map Widget

# %%
# parameters

dwell_map_widget_params = dict(
    view=...,
)

# %%
# call the task


dwell_map_widget = (
    create_map_widget_single_view.set_task_instance_id("dwell_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Time Spent Per Grid Cell (Hours)",
        data=dwell_urls,
        **dwell_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Create Linear Time Density Map Widget

# %%
# parameters

ltd_map_widget_params = dict(
    view=...,
)

# %%
# call the task


ltd_map_widget = (
    create_map_widget_single_view.set_task_instance_id("ltd_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(title="Patrol Linear Time Density", data=ltd_urls, **ltd_map_widget_params)
    .call()
)


# %% [markdown]
# ## Render Operational Days Table

# %%
# parameters

op_summary_table_html_params = dict()

# %%
# call the task


op_summary_table_html = (
    draw_table.set_task_instance_id("op_summary_table_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=op_summary_table,
        columns=None,
        table_config={
            "enable_sorting": True,
            "enable_filtering": True,
            "enable_download": False,
            "hide_header": False,
        },
        widget_id="Operational Days Summary",
        **op_summary_table_html_params,
    )
    .call()
)


# %% [markdown]
# ## Save Operational Days Table (HTML)

# %%
# parameters

op_summary_table_html_url_params = dict(
    filename=...,
)

# %%
# call the task


op_summary_table_html_url = (
    persist_text.set_task_instance_id("op_summary_table_html_url")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="op_summary_table",
        text=op_summary_table_html,
        **op_summary_table_html_url_params,
    )
    .call()
)


# %% [markdown]
# ## Create Operational Summary Table Widget

# %%
# parameters

op_summary_table_widget_params = dict(
    view=...,
)

# %%
# call the task


op_summary_table_widget = (
    create_table_widget_single_view.set_task_instance_id("op_summary_table_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Operational Days Summary",
        data=op_summary_table_html_url,
        **op_summary_table_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Generate Dashboard

# %%
# parameters

patrol_effort_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


patrol_effort_dashboard = (
    gather_dashboard.set_task_instance_id("patrol_effort_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[
            total_patrols_sv_widget,
            total_patrol_dist_sv_widget,
            patrol_effort_sv_widget,
            time_since_map_widget,
            dwell_map_widget,
            ltd_map_widget,
            op_summary_table_widget,
        ],
        time_range=time_range,
        groupers=groupers,
        **patrol_effort_dashboard_params,
    )
    .call()
)
