# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)

get_patrol_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_patrol_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    view_state_from_geodataframes as view_state_from_geodataframes,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    assert_polygon_types as assert_polygon_types,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import spatial_join as spatial_join
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    to_quantity as to_quantity,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_bin_colors as add_bin_colors,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_index_column as add_index_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_non_null_flag as add_non_null_flag,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_time_since_visit as add_time_since_visit,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_visit_bins as add_visit_bins,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    compute_dwell_time as compute_dwell_time,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    compute_patrol_effort_fraction as compute_patrol_effort_fraction,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    hex_column_to_rgba as hex_column_to_rgba,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    operational_days as operational_days,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    order_bin_categories as order_bin_categories,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    overlay_gdf as overlay_gdf,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    reset_df_index as reset_df_index,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    set_spatial_features_opacity as set_spatial_features_opacity,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_linear_time_density as calculate_linear_time_density,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    create_meshgrid as create_meshgrid,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    base_map_defs = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("base_map_defs") or {}))
        .call()
    )

    select_geo_er = (
        get_spatial_features.validate()
        .set_task_instance_id("select_geo_er")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            legend_title="Legend",
            **(params_dict.get("select_geo_er") or {}),
        )
        .call()
    )

    get_patrol_obs = (
        get_patrol_observations.validate()
        .set_task_instance_id("get_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            status=["done"],
            include_patrol_details=True,
            raise_on_empty=True,
            sub_page_size=100,
            patrols_overlap_daterange=True,
            **(params_dict.get("get_patrol_obs") or {}),
        )
        .call()
    )

    patrol_obs_trajs = (
        relocations_to_trajectory.validate()
        .set_task_instance_id("patrol_obs_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=get_patrol_obs, **(params_dict.get("patrol_obs_trajs") or {})
        )
        .call()
    )

    assert_polygon = (
        assert_polygon_types.validate()
        .set_task_instance_id("assert_polygon")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(gdf=select_geo_er, **(params_dict.get("assert_polygon") or {}))
        .call()
    )

    reproject_spatial_3857 = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_spatial_3857")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=select_geo_er,
            target_crs="EPSG:3857",
            **(params_dict.get("reproject_spatial_3857") or {}),
        )
        .call()
    )

    persist_spatial_file = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_spatial_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_spatial_3857,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="spatial_file",
            filetypes=["geoparquet"],
            filename_prefix="er_spatial_file",
            sanitize=True,
            **(params_dict.get("persist_spatial_file") or {}),
        )
        .call()
    )

    create_geo_meshgrid = (
        create_meshgrid.validate()
        .set_task_instance_id("create_geo_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=reproject_spatial_3857,
            crs="EPSG:3857",
            intersecting_only=True,
            **(params_dict.get("create_geo_meshgrid") or {}),
        )
        .call()
    )

    overlay_meshgrid_spatial = (
        overlay_gdf.validate()
        .set_task_instance_id("overlay_meshgrid_spatial")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=create_geo_meshgrid,
            right=reproject_spatial_3857,
            how="intersection",
            keep_geom_type=True,
            make_valid=True,
            **(params_dict.get("overlay_meshgrid_spatial") or {}),
        )
        .call()
    )

    meshgrid_idx_id = (
        add_index_column.validate()
        .set_task_instance_id("meshgrid_idx_id")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=overlay_meshgrid_spatial,
            column="cell_id",
            **(params_dict.get("meshgrid_idx_id") or {}),
        )
        .call()
    )

    reproject_trajs = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=patrol_obs_trajs,
            target_crs="EPSG:3857",
            **(params_dict.get("reproject_trajs") or {}),
        )
        .call()
    )

    select_patrol_columns = (
        select_columns.validate()
        .set_task_instance_id("select_patrol_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_trajs,
            columns=["segment_start", "segment_end", "geometry"],
            raise_on_missing=True,
            **(params_dict.get("select_patrol_columns") or {}),
        )
        .call()
    )

    spatial_join_patrol_trajs = (
        spatial_join.validate()
        .set_task_instance_id("spatial_join_patrol_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left_df=select_patrol_columns,
            right_df=meshgrid_idx_id,
            how="inner",
            predicate="intersects",
            **(params_dict.get("spatial_join_patrol_trajs") or {}),
        )
        .call()
    )

    summarize_df_grids = (
        summarize_df.validate()
        .set_task_instance_id("summarize_df_grids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=spatial_join_patrol_trajs,
            groupby_cols=["cell_id"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "last_visited",
                    "aggregator": "max",
                    "column": "segment_end",
                    "original_unit": None,
                    "new_unit": None,
                    "decimal_places": None,
                },
                {
                    "display_name": "first_visited",
                    "aggregator": "min",
                    "column": "segment_start",
                    "original_unit": None,
                    "new_unit": None,
                    "decimal_places": None,
                },
            ],
            **(params_dict.get("summarize_df_grids") or {}),
        )
        .call()
    )

    add_time = (
        add_time_since_visit.validate()
        .set_task_instance_id("add_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=summarize_df_grids,
            time_range=time_range,
            **(params_dict.get("add_time") or {}),
        )
        .call()
    )

    merge_gridded_stats = (
        merge_two_dataframes.validate()
        .set_task_instance_id("merge_gridded_stats")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=meshgrid_idx_id,
            right=add_time,
            how="left",
            on="cell_id",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params_dict.get("merge_gridded_stats") or {}),
        )
        .call()
    )

    add_null_flag = (
        add_non_null_flag.validate()
        .set_task_instance_id("add_null_flag")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=merge_gridded_stats,
            source_column="days_since_visit",
            flag_column="visited",
            **(params_dict.get("add_null_flag") or {}),
        )
        .call()
    )

    add_custom_visit_bins = (
        add_visit_bins.validate()
        .set_task_instance_id("add_custom_visit_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_null_flag,
            col="days_since_visit",
            visited_col="visited",
            new_col="visit_bin",
            bins=5,
            scheme="natural_breaks",
            **(params_dict.get("add_custom_visit_bins") or {}),
        )
        .call()
    )

    add_visit_bin_colors = (
        add_bin_colors.validate()
        .set_task_instance_id("add_visit_bin_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_custom_visit_bins,
            col="visit_bin",
            new_col="hex_color",
            cmap={"type_": "palette", "name": "RdYlGn_r"},
            unvisited="#808080",
            **(params_dict.get("add_visit_bin_colors") or {}),
        )
        .call()
    )

    reproject_4326 = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_4326")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=add_visit_bin_colors,
            target_crs="EPSG:4326",
            **(params_dict.get("reproject_4326") or {}),
        )
        .call()
    )

    persist_visit = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_visit")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_4326,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filetypes=["geoparquet"],
            filename_prefix="days_since_patrol_visit",
            sanitize=True,
            **(params_dict.get("persist_visit") or {}),
        )
        .call()
    )

    reset_patrol_trajs = (
        reset_df_index.validate()
        .set_task_instance_id("reset_patrol_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_trajs,
            drop=False,
            **(params_dict.get("reset_patrol_trajs") or {}),
        )
        .call()
    )

    compute_patrol_dwell = (
        compute_dwell_time.validate()
        .set_task_instance_id("compute_patrol_dwell")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrol_trajectories=reset_patrol_trajs,
            gridded_spatial_feature=meshgrid_idx_id,
            **(params_dict.get("compute_patrol_dwell") or {}),
        )
        .call()
    )

    merge_dwell_gdf = (
        merge_two_dataframes.validate()
        .set_task_instance_id("merge_dwell_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=meshgrid_idx_id,
            right=compute_patrol_dwell,
            how="left",
            on="cell_id",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params_dict.get("merge_dwell_gdf") or {}),
        )
        .call()
    )

    reproject_dwell_gdf = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_dwell_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=merge_dwell_gdf,
            target_crs="EPSG:4326",
            **(params_dict.get("reproject_dwell_gdf") or {}),
        )
        .call()
    )

    add_null_dwell_flag = (
        add_non_null_flag.validate()
        .set_task_instance_id("add_null_dwell_flag")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_dwell_gdf,
            source_column="hours_in_cell",
            flag_column="visited",
            **(params_dict.get("add_null_dwell_flag") or {}),
        )
        .call()
    )

    add_custom_dwell_bins = (
        add_visit_bins.validate()
        .set_task_instance_id("add_custom_dwell_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_null_dwell_flag,
            col="hours_in_cell",
            visited_col="visited",
            new_col="visit_bin",
            bins=5,
            scheme="natural_breaks",
            **(params_dict.get("add_custom_dwell_bins") or {}),
        )
        .call()
    )

    add_dwell_bin_colors = (
        add_bin_colors.validate()
        .set_task_instance_id("add_dwell_bin_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_custom_dwell_bins,
            col="visit_bin",
            new_col="hex_color",
            cmap={"type_": "palette", "name": "RdYlGn"},
            unvisited="#808080",
            **(params_dict.get("add_dwell_bin_colors") or {}),
        )
        .call()
    )

    persist_dwell_geoparquet = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_dwell_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_dwell_bin_colors,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filetypes=["geoparquet"],
            filename_prefix="time_spent_per_cell",
            sanitize=True,
            **(params_dict.get("persist_dwell_geoparquet") or {}),
        )
        .call()
    )

    calc_ltd_aoi = (
        calculate_linear_time_density.validate()
        .set_task_instance_id("calc_ltd_aoi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            percentiles=None,
            trajectory_gdf=reproject_trajs,
            meshgrid=overlay_meshgrid_spatial,
            **(params_dict.get("calc_ltd_aoi") or {}),
        )
        .call()
    )

    persist_ltd_geoparquet = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_ltd_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=calc_ltd_aoi,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filetypes=["geoparquet"],
            filename_prefix="patrols_linear_time_density",
            sanitize=True,
            **(params_dict.get("persist_ltd_geoparquet") or {}),
        )
        .call()
    )

    reproject_ltd = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_ltd")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=calc_ltd_aoi,
            target_crs="EPSG:4326",
            **(params_dict.get("reproject_ltd") or {}),
        )
        .call()
    )

    add_null_ltd_flag = (
        add_non_null_flag.validate()
        .set_task_instance_id("add_null_ltd_flag")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_ltd,
            source_column="percentile",
            flag_column="visited",
            **(params_dict.get("add_null_ltd_flag") or {}),
        )
        .call()
    )

    add_custom_ltd_bins = (
        add_visit_bins.validate()
        .set_task_instance_id("add_custom_ltd_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_null_ltd_flag,
            col="percentile",
            visited_col="visited",
            new_col="visit_bin",
            bins=5,
            scheme="natural_breaks",
            **(params_dict.get("add_custom_ltd_bins") or {}),
        )
        .call()
    )

    add_ltd_bin_colors = (
        add_bin_colors.validate()
        .set_task_instance_id("add_ltd_bin_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_custom_ltd_bins,
            col="visit_bin",
            new_col="hex_color",
            cmap={"type_": "palette", "name": "RdYlGn"},
            unvisited="#808080",
            **(params_dict.get("add_ltd_bin_colors") or {}),
        )
        .call()
    )

    rename_patrol_cols = (
        map_columns.validate()
        .set_task_instance_id("rename_patrol_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            df=reproject_trajs,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__patrol_type__value": "patrol_type",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_status": "patrol_status",
                "extra__patrol_subject": "Name",
                "extra__subject_id": "ID",
            },
            **(params_dict.get("rename_patrol_cols") or {}),
        )
        .call()
    )

    op_summary_table = (
        operational_days.validate()
        .set_task_instance_id("op_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajs=rename_patrol_cols,
            segment_start="segment_start",
            segment_end="segment_end",
            groupby_cols=["ID", "Name"],
            **(params_dict.get("op_summary_table") or {}),
        )
        .call()
    )

    persist_oper_table = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_oper_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=op_summary_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filetypes=["csv"],
            filename_prefix="patrol_operational_days",
            sanitize=False,
            **(params_dict.get("persist_oper_table") or {}),
        )
        .call()
    )

    persist_patrol_obs = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_patrol_obs,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filetypes=["geoparquet"],
            filename_prefix="patrol_observations",
            sanitize=True,
            **(params_dict.get("persist_patrol_obs") or {}),
        )
        .call()
    )

    persist_patrol_trajs = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_patrol_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs_trajs,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filetypes=["geoparquet"],
            filename_prefix="patrol_trajectories",
            sanitize=True,
            **(params_dict.get("persist_patrol_trajs") or {}),
        )
        .call()
    )

    spatial_features_opacity = (
        set_spatial_features_opacity.validate()
        .set_task_instance_id("spatial_features_opacity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=select_geo_er,
            fill_opacity=0.0,
            line_opacity=1.0,
            **(params_dict.get("spatial_features_opacity") or {}),
        )
        .call()
    )

    spatial_features_layer = (
        create_spatial_features_layer.validate()
        .set_task_instance_id("spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=spatial_features_opacity,
            **(params_dict.get("spatial_features_layer") or {}),
        )
        .call()
    )

    overall_zoom_value = (
        view_state_from_geodataframes.validate()
        .set_task_instance_id("overall_zoom_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframes=[select_geo_er],
            max_zoom=15,
            **(params_dict.get("overall_zoom_value") or {}),
        )
        .call()
    )

    add_time_visit_rgba = (
        hex_column_to_rgba.validate()
        .set_task_instance_id("add_time_visit_rgba")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=reproject_4326,
            column="hex_color",
            new_column="rgba_color",
            **(params_dict.get("add_time_visit_rgba") or {}),
        )
        .call()
    )

    order_bin_visit_since = (
        order_bin_categories.validate()
        .set_task_instance_id("order_bin_visit_since")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_time_visit_rgba,
            bin_column="visit_bin",
            **(params_dict.get("order_bin_visit_since") or {}),
        )
        .call()
    )

    create_time_since_layer = (
        create_geojson_layer.validate()
        .set_task_instance_id("create_time_since_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            geodataframe=order_bin_visit_since,
            layer_style={
                "filled": True,
                "extruded": False,
                "stroked": True,
                "get_fill_color": "rgba_color",
                "get_line_color": [0, 0, 0],
                "opacity": 0.55,
                "get_line_width": 0.25,
            },
            legend={
                "title": "Time Since Visit (Days)",
                "label_column": "visit_bin",
                "color_column": "rgba_color",
                "sort": "ascending",
                "label_suffix": None,
            },
            **(params_dict.get("create_time_since_layer") or {}),
        )
        .call()
    )

    draw_time_since_map = (
        draw_map.validate()
        .set_task_instance_id("draw_time_since_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            max_zoom=10,
            static=False,
            title=None,
            geo_layers=[create_time_since_layer, spatial_features_layer],
            tile_layers=base_map_defs,
            legend_style={"placement": "bottom-right"},
            view_state=overall_zoom_value,
            **(params_dict.get("draw_time_since_map") or {}),
        )
        .call()
    )

    time_since_urls = (
        persist_text.validate()
        .set_task_instance_id("time_since_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_time_since_map,
            filename="days_since_patrol_visit_map.html",
            **(params_dict.get("time_since_urls") or {}),
        )
        .call()
    )

    add_dwell_rgba = (
        hex_column_to_rgba.validate()
        .set_task_instance_id("add_dwell_rgba")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_dwell_bin_colors,
            column="hex_color",
            new_column="rgba_color",
            **(params_dict.get("add_dwell_rgba") or {}),
        )
        .call()
    )

    order_bin_dwell_since = (
        order_bin_categories.validate()
        .set_task_instance_id("order_bin_dwell_since")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_dwell_rgba,
            bin_column="visit_bin",
            **(params_dict.get("order_bin_dwell_since") or {}),
        )
        .call()
    )

    create_dwell_layer = (
        create_geojson_layer.validate()
        .set_task_instance_id("create_dwell_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            geodataframe=order_bin_dwell_since,
            layer_style={
                "filled": True,
                "extruded": False,
                "stroked": True,
                "get_fill_color": "rgba_color",
                "get_line_color": [0, 0, 0],
                "opacity": 0.55,
                "get_line_width": 0.25,
            },
            legend={
                "title": "Time Spent(Hours)",
                "label_column": "visit_bin",
                "color_column": "rgba_color",
                "sort": "ascending",
                "label_suffix": None,
            },
            **(params_dict.get("create_dwell_layer") or {}),
        )
        .call()
    )

    draw_dwell_map = (
        draw_map.validate()
        .set_task_instance_id("draw_dwell_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            max_zoom=10,
            static=False,
            title=None,
            geo_layers=[create_dwell_layer, spatial_features_layer],
            tile_layers=base_map_defs,
            legend_style={"placement": "bottom-right"},
            view_state=overall_zoom_value,
            **(params_dict.get("draw_dwell_map") or {}),
        )
        .call()
    )

    dwell_urls = (
        persist_text.validate()
        .set_task_instance_id("dwell_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_dwell_map,
            filename="time_spent_per_grid_map.html",
            **(params_dict.get("dwell_urls") or {}),
        )
        .call()
    )

    add_ltd_rgba = (
        hex_column_to_rgba.validate()
        .set_task_instance_id("add_ltd_rgba")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_ltd_bin_colors,
            column="hex_color",
            new_column="rgba_color",
            **(params_dict.get("add_ltd_rgba") or {}),
        )
        .call()
    )

    order_bin_ltd_since = (
        order_bin_categories.validate()
        .set_task_instance_id("order_bin_ltd_since")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_ltd_rgba,
            bin_column="visit_bin",
            **(params_dict.get("order_bin_ltd_since") or {}),
        )
        .call()
    )

    create_ltd_layer = (
        create_geojson_layer.validate()
        .set_task_instance_id("create_ltd_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            geodataframe=order_bin_ltd_since,
            layer_style={
                "filled": True,
                "extruded": False,
                "stroked": True,
                "get_fill_color": "rgba_color",
                "get_line_color": [0, 0, 0],
                "opacity": 0.55,
                "get_line_width": 0.25,
            },
            legend={
                "title": "Time Spent",
                "label_column": "visit_bin",
                "color_column": "rgba_color",
                "sort": "ascending",
                "label_suffix": None,
            },
            **(params_dict.get("create_ltd_layer") or {}),
        )
        .call()
    )

    draw_ltd_map = (
        draw_map.validate()
        .set_task_instance_id("draw_ltd_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            max_zoom=10,
            static=False,
            title=None,
            geo_layers=[create_ltd_layer, spatial_features_layer],
            tile_layers=base_map_defs,
            legend_style={"placement": "bottom-right"},
            view_state=overall_zoom_value,
            **(params_dict.get("draw_ltd_map") or {}),
        )
        .call()
    )

    ltd_urls = (
        persist_text.validate()
        .set_task_instance_id("ltd_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_ltd_map,
            filename="ltd_patrols_map.html",
            **(params_dict.get("ltd_urls") or {}),
        )
        .call()
    )

    total_patrols = (
        dataframe_column_nunique.validate()
        .set_task_instance_id("total_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="ID",
            df=rename_patrol_cols,
            **(params_dict.get("total_patrols") or {}),
        )
        .call()
    )

    total_patrol_dist = (
        dataframe_column_sum.validate()
        .set_task_instance_id("total_patrol_dist")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="dist_meters",
            df=rename_patrol_cols,
            **(params_dict.get("total_patrol_dist") or {}),
        )
        .call()
    )

    total_patrol_dist_converted = (
        with_unit.validate()
        .set_task_instance_id("total_patrol_dist_converted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="m",
            new_unit="km",
            value=total_patrol_dist,
            **(params_dict.get("total_patrol_dist_converted") or {}),
        )
        .call()
    )

    patrol_effort_spatial = (
        compute_patrol_effort_fraction.validate()
        .set_task_instance_id("patrol_effort_spatial")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=add_visit_bin_colors, **(params_dict.get("patrol_effort_spatial") or {})
        )
        .call()
    )

    total_patrols_sv_widget = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_patrols_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Patrols",
            decimal_places=0,
            data=total_patrols,
            **(params_dict.get("total_patrols_sv_widget") or {}),
        )
        .call()
    )

    total_patrol_dist_sv_widget = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_patrol_dist_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Patrol Distance",
            decimal_places=1,
            data=total_patrol_dist_converted,
            **(params_dict.get("total_patrol_dist_sv_widget") or {}),
        )
        .call()
    )

    patrol_effort_quantity = (
        to_quantity.validate()
        .set_task_instance_id("patrol_effort_quantity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value=patrol_effort_spatial,
            unit="%",
            **(params_dict.get("patrol_effort_quantity") or {}),
        )
        .call()
    )

    patrol_effort_sv_widget = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("patrol_effort_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Coverage",
            decimal_places=1,
            data=patrol_effort_quantity,
            **(params_dict.get("patrol_effort_sv_widget") or {}),
        )
        .call()
    )

    time_since_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("time_since_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Days Since Patrol Visit",
            data=time_since_urls,
            **(params_dict.get("time_since_map_widget") or {}),
        )
        .call()
    )

    dwell_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("dwell_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Time Spent Per Grid Cell (Hours)",
            data=dwell_urls,
            **(params_dict.get("dwell_map_widget") or {}),
        )
        .call()
    )

    ltd_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("ltd_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Linear Time Density",
            data=ltd_urls,
            **(params_dict.get("ltd_map_widget") or {}),
        )
        .call()
    )

    op_summary_table_html = (
        draw_table.validate()
        .set_task_instance_id("op_summary_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=op_summary_table,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Operational Days Summary",
            **(params_dict.get("op_summary_table_html") or {}),
        )
        .call()
    )

    op_summary_table_html_url = (
        persist_text.validate()
        .set_task_instance_id("op_summary_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="op_summary_table",
            text=op_summary_table_html,
            **(params_dict.get("op_summary_table_html_url") or {}),
        )
        .call()
    )

    op_summary_table_widget = (
        create_table_widget_single_view.validate()
        .set_task_instance_id("op_summary_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Operational Days Summary",
            data=op_summary_table_html_url,
            **(params_dict.get("op_summary_table_widget") or {}),
        )
        .call()
    )

    patrol_effort_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("patrol_effort_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_patrols_sv_widget,
                total_patrol_dist_sv_widget,
                patrol_effort_sv_widget,
                time_since_map_widget,
                dwell_map_widget,
                ltd_map_widget,
                op_summary_table_widget,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("patrol_effort_dashboard") or {}),
        )
        .call()
    )

    return patrol_effort_dashboard
