# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    view_state_from_geodataframes as view_state_from_geodataframes,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    assert_polygon_types as assert_polygon_types,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import spatial_join as spatial_join
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    to_quantity as to_quantity,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_bin_colors as add_bin_colors,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_index_column as add_index_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_non_null_flag as add_non_null_flag,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_time_since_visit as add_time_since_visit,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    add_visit_bins as add_visit_bins,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    compute_dwell_time as compute_dwell_time,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    compute_patrol_effort_fraction as compute_patrol_effort_fraction,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    hex_column_to_rgba as hex_column_to_rgba,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    operational_days as operational_days,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    order_bin_categories as order_bin_categories,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    overlay_gdf as overlay_gdf,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    reset_df_index as reset_df_index,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks import (
    set_spatial_features_opacity as set_spatial_features_opacity,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_linear_time_density as calculate_linear_time_density,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    create_meshgrid as create_meshgrid,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrol_observations as get_patrol_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "er_client_name": [],
        "groupers": [],
        "time_range": [],
        "base_map_defs": [],
        "select_geo_er": ["er_client_name"],
        "get_patrol_obs": ["er_client_name", "time_range"],
        "patrol_obs_trajs": ["get_patrol_obs"],
        "assert_polygon": ["select_geo_er"],
        "reproject_spatial_3857": ["select_geo_er"],
        "persist_spatial_file": ["reproject_spatial_3857"],
        "create_geo_meshgrid": ["reproject_spatial_3857"],
        "overlay_meshgrid_spatial": ["create_geo_meshgrid", "reproject_spatial_3857"],
        "meshgrid_idx_id": ["overlay_meshgrid_spatial"],
        "reproject_trajs": ["patrol_obs_trajs"],
        "select_patrol_columns": ["reproject_trajs"],
        "spatial_join_patrol_trajs": ["select_patrol_columns", "meshgrid_idx_id"],
        "summarize_df_grids": ["spatial_join_patrol_trajs"],
        "add_time": ["summarize_df_grids", "time_range"],
        "merge_gridded_stats": ["meshgrid_idx_id", "add_time"],
        "add_null_flag": ["merge_gridded_stats"],
        "add_custom_visit_bins": ["add_null_flag"],
        "add_visit_bin_colors": ["add_custom_visit_bins"],
        "reproject_4326": ["add_visit_bin_colors"],
        "persist_visit": ["reproject_4326"],
        "reset_patrol_trajs": ["reproject_trajs"],
        "compute_patrol_dwell": ["reset_patrol_trajs", "meshgrid_idx_id"],
        "merge_dwell_gdf": ["meshgrid_idx_id", "compute_patrol_dwell"],
        "reproject_dwell_gdf": ["merge_dwell_gdf"],
        "add_null_dwell_flag": ["reproject_dwell_gdf"],
        "add_custom_dwell_bins": ["add_null_dwell_flag"],
        "add_dwell_bin_colors": ["add_custom_dwell_bins"],
        "persist_dwell_gkpg": ["add_dwell_bin_colors"],
        "calc_ltd_aoi": ["reproject_trajs", "overlay_meshgrid_spatial"],
        "persist_ltd_gkpg": ["calc_ltd_aoi"],
        "reproject_ltd": ["calc_ltd_aoi"],
        "add_null_ltd_flag": ["reproject_ltd"],
        "add_custom_ltd_bins": ["add_null_ltd_flag"],
        "add_ltd_bin_colors": ["add_custom_ltd_bins"],
        "rename_patrol_cols": ["reproject_trajs"],
        "op_summary_table": ["rename_patrol_cols"],
        "persist_oper_table": ["op_summary_table"],
        "persist_patrol_obs": ["get_patrol_obs"],
        "persist_patrol_trajs": ["patrol_obs_trajs"],
        "spatial_features_opacity": ["select_geo_er"],
        "spatial_features_layer": ["spatial_features_opacity"],
        "overall_zoom_value": ["select_geo_er"],
        "add_time_visit_rgba": ["reproject_4326"],
        "order_bin_visit_since": ["add_time_visit_rgba"],
        "create_time_since_layer": ["order_bin_visit_since"],
        "draw_time_since_map": [
            "create_time_since_layer",
            "spatial_features_layer",
            "base_map_defs",
            "overall_zoom_value",
        ],
        "time_since_urls": ["draw_time_since_map"],
        "add_dwell_rgba": ["add_dwell_bin_colors"],
        "order_bin_dwell_since": ["add_dwell_rgba"],
        "create_dwell_layer": ["order_bin_dwell_since"],
        "draw_dwell_map": [
            "create_dwell_layer",
            "spatial_features_layer",
            "base_map_defs",
            "overall_zoom_value",
        ],
        "dwell_urls": ["draw_dwell_map"],
        "add_ltd_rgba": ["add_ltd_bin_colors"],
        "order_bin_ltd_since": ["add_ltd_rgba"],
        "create_ltd_layer": ["order_bin_ltd_since"],
        "draw_ltd_map": [
            "create_ltd_layer",
            "spatial_features_layer",
            "base_map_defs",
            "overall_zoom_value",
        ],
        "ltd_urls": ["draw_ltd_map"],
        "total_patrols": ["rename_patrol_cols"],
        "total_patrol_dist": ["rename_patrol_cols"],
        "total_patrol_dist_converted": ["total_patrol_dist"],
        "patrol_effort_spatial": ["add_visit_bin_colors"],
        "total_patrols_sv_widget": ["total_patrols"],
        "total_patrol_dist_sv_widget": ["total_patrol_dist_converted"],
        "patrol_effort_quantity": ["patrol_effort_spatial"],
        "patrol_effort_sv_widget": ["patrol_effort_quantity"],
        "time_since_map_widget": ["time_since_urls"],
        "dwell_map_widget": ["dwell_urls"],
        "ltd_map_widget": ["ltd_urls"],
        "op_summary_table_html": ["op_summary_table"],
        "op_summary_table_html_url": ["op_summary_table_html"],
        "op_summary_table_widget": ["op_summary_table_html_url"],
        "patrol_effort_dashboard": [
            "workflow_details",
            "total_patrols_sv_widget",
            "total_patrol_dist_sv_widget",
            "patrol_effort_sv_widget",
            "time_since_map_widget",
            "dwell_map_widget",
            "ltd_map_widget",
            "op_summary_table_widget",
            "time_range",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={} | (params_dict.get("groupers") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "base_map_defs": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "select_geo_er": Node(
            async_task=get_spatial_features.validate()
            .set_task_instance_id("select_geo_er")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "legend_title": "Legend",
            }
            | (params_dict.get("select_geo_er") or {}),
            method="call",
        ),
        "get_patrol_obs": Node(
            async_task=get_patrol_observations.validate()
            .set_task_instance_id("get_patrol_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "status": [
                    "done",
                ],
                "include_patrol_details": True,
                "raise_on_empty": True,
                "sub_page_size": 100,
                "patrols_overlap_daterange": True,
            }
            | (params_dict.get("get_patrol_obs") or {}),
            method="call",
        ),
        "patrol_obs_trajs": Node(
            async_task=relocations_to_trajectory.validate()
            .set_task_instance_id("patrol_obs_trajs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("get_patrol_obs"),
            }
            | (params_dict.get("patrol_obs_trajs") or {}),
            method="call",
        ),
        "assert_polygon": Node(
            async_task=assert_polygon_types.validate()
            .set_task_instance_id("assert_polygon")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("select_geo_er"),
            }
            | (params_dict.get("assert_polygon") or {}),
            method="call",
        ),
        "reproject_spatial_3857": Node(
            async_task=reproject_gdf.validate()
            .set_task_instance_id("reproject_spatial_3857")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("select_geo_er"),
                "target_crs": "EPSG:3857",
            }
            | (params_dict.get("reproject_spatial_3857") or {}),
            method="call",
        ),
        "persist_spatial_file": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_spatial_file")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("reproject_spatial_3857"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename": "spatial_file",
                "filetypes": [
                    "gpkg",
                ],
                "filename_prefix": "er_spatial_file",
                "sanitize": False,
            }
            | (params_dict.get("persist_spatial_file") or {}),
            method="call",
        ),
        "create_geo_meshgrid": Node(
            async_task=create_meshgrid.validate()
            .set_task_instance_id("create_geo_meshgrid")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "aoi": DependsOn("reproject_spatial_3857"),
                "crs": "EPSG:3857",
                "intersecting_only": True,
            }
            | (params_dict.get("create_geo_meshgrid") or {}),
            method="call",
        ),
        "overlay_meshgrid_spatial": Node(
            async_task=overlay_gdf.validate()
            .set_task_instance_id("overlay_meshgrid_spatial")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "left": DependsOn("create_geo_meshgrid"),
                "right": DependsOn("reproject_spatial_3857"),
                "how": "intersection",
                "keep_geom_type": True,
                "make_valid": True,
            }
            | (params_dict.get("overlay_meshgrid_spatial") or {}),
            method="call",
        ),
        "meshgrid_idx_id": Node(
            async_task=add_index_column.validate()
            .set_task_instance_id("meshgrid_idx_id")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("overlay_meshgrid_spatial"),
                "column": "cell_id",
            }
            | (params_dict.get("meshgrid_idx_id") or {}),
            method="call",
        ),
        "reproject_trajs": Node(
            async_task=reproject_gdf.validate()
            .set_task_instance_id("reproject_trajs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("patrol_obs_trajs"),
                "target_crs": "EPSG:3857",
            }
            | (params_dict.get("reproject_trajs") or {}),
            method="call",
        ),
        "select_patrol_columns": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("select_patrol_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("reproject_trajs"),
                "columns": [
                    "segment_start",
                    "segment_end",
                    "geometry",
                ],
                "raise_on_missing": True,
            }
            | (params_dict.get("select_patrol_columns") or {}),
            method="call",
        ),
        "spatial_join_patrol_trajs": Node(
            async_task=spatial_join.validate()
            .set_task_instance_id("spatial_join_patrol_trajs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "left_df": DependsOn("select_patrol_columns"),
                "right_df": DependsOn("meshgrid_idx_id"),
                "how": "inner",
                "predicate": "intersects",
            }
            | (params_dict.get("spatial_join_patrol_trajs") or {}),
            method="call",
        ),
        "summarize_df_grids": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("summarize_df_grids")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("spatial_join_patrol_trajs"),
                "groupby_cols": [
                    "cell_id",
                ],
                "reset_index": True,
                "summary_params": [
                    {
                        "display_name": "last_visited",
                        "aggregator": "max",
                        "column": "segment_end",
                        "original_unit": None,
                        "new_unit": None,
                        "decimal_places": None,
                    },
                    {
                        "display_name": "first_visited",
                        "aggregator": "min",
                        "column": "segment_start",
                        "original_unit": None,
                        "new_unit": None,
                        "decimal_places": None,
                    },
                ],
            }
            | (params_dict.get("summarize_df_grids") or {}),
            method="call",
        ),
        "add_time": Node(
            async_task=add_time_since_visit.validate()
            .set_task_instance_id("add_time")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("summarize_df_grids"),
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("add_time") or {}),
            method="call",
        ),
        "merge_gridded_stats": Node(
            async_task=merge_two_dataframes.validate()
            .set_task_instance_id("merge_gridded_stats")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "left": DependsOn("meshgrid_idx_id"),
                "right": DependsOn("add_time"),
                "how": "left",
                "on": "cell_id",
                "left_on": None,
                "right_on": None,
                "left_index": False,
                "right_index": False,
                "fillna_value": None,
            }
            | (params_dict.get("merge_gridded_stats") or {}),
            method="call",
        ),
        "add_null_flag": Node(
            async_task=add_non_null_flag.validate()
            .set_task_instance_id("add_null_flag")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("merge_gridded_stats"),
                "source_column": "days_since_visit",
                "flag_column": "visited",
            }
            | (params_dict.get("add_null_flag") or {}),
            method="call",
        ),
        "add_custom_visit_bins": Node(
            async_task=add_visit_bins.validate()
            .set_task_instance_id("add_custom_visit_bins")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_null_flag"),
                "col": "days_since_visit",
                "visited_col": "visited",
                "new_col": "visit_bin",
                "bins": 5,
                "scheme": "natural_breaks",
            }
            | (params_dict.get("add_custom_visit_bins") or {}),
            method="call",
        ),
        "add_visit_bin_colors": Node(
            async_task=add_bin_colors.validate()
            .set_task_instance_id("add_visit_bin_colors")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_custom_visit_bins"),
                "col": "visit_bin",
                "new_col": "hex_color",
                "cmap": {
                    "type_": "palette",
                    "name": "RdYlGn_r",
                },
                "unvisited": "#808080",
            }
            | (params_dict.get("add_visit_bin_colors") or {}),
            method="call",
        ),
        "reproject_4326": Node(
            async_task=reproject_gdf.validate()
            .set_task_instance_id("reproject_4326")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("add_visit_bin_colors"),
                "target_crs": "EPSG:4326",
            }
            | (params_dict.get("reproject_4326") or {}),
            method="call",
        ),
        "persist_visit": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_visit")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("reproject_4326"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename": None,
                "filetypes": [
                    "gpkg",
                ],
                "filename_prefix": "days_since_patrol_visit",
                "sanitize": False,
            }
            | (params_dict.get("persist_visit") or {}),
            method="call",
        ),
        "reset_patrol_trajs": Node(
            async_task=reset_df_index.validate()
            .set_task_instance_id("reset_patrol_trajs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("reproject_trajs"),
                "drop": False,
            }
            | (params_dict.get("reset_patrol_trajs") or {}),
            method="call",
        ),
        "compute_patrol_dwell": Node(
            async_task=compute_dwell_time.validate()
            .set_task_instance_id("compute_patrol_dwell")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "patrol_trajectories": DependsOn("reset_patrol_trajs"),
                "gridded_spatial_feature": DependsOn("meshgrid_idx_id"),
            }
            | (params_dict.get("compute_patrol_dwell") or {}),
            method="call",
        ),
        "merge_dwell_gdf": Node(
            async_task=merge_two_dataframes.validate()
            .set_task_instance_id("merge_dwell_gdf")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "left": DependsOn("meshgrid_idx_id"),
                "right": DependsOn("compute_patrol_dwell"),
                "how": "left",
                "on": "cell_id",
                "left_on": None,
                "right_on": None,
                "left_index": False,
                "right_index": False,
                "fillna_value": None,
            }
            | (params_dict.get("merge_dwell_gdf") or {}),
            method="call",
        ),
        "reproject_dwell_gdf": Node(
            async_task=reproject_gdf.validate()
            .set_task_instance_id("reproject_dwell_gdf")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("merge_dwell_gdf"),
                "target_crs": "EPSG:4326",
            }
            | (params_dict.get("reproject_dwell_gdf") or {}),
            method="call",
        ),
        "add_null_dwell_flag": Node(
            async_task=add_non_null_flag.validate()
            .set_task_instance_id("add_null_dwell_flag")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("reproject_dwell_gdf"),
                "source_column": "hours_in_cell",
                "flag_column": "visited",
            }
            | (params_dict.get("add_null_dwell_flag") or {}),
            method="call",
        ),
        "add_custom_dwell_bins": Node(
            async_task=add_visit_bins.validate()
            .set_task_instance_id("add_custom_dwell_bins")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_null_dwell_flag"),
                "col": "hours_in_cell",
                "visited_col": "visited",
                "new_col": "visit_bin",
                "bins": 5,
                "scheme": "natural_breaks",
            }
            | (params_dict.get("add_custom_dwell_bins") or {}),
            method="call",
        ),
        "add_dwell_bin_colors": Node(
            async_task=add_bin_colors.validate()
            .set_task_instance_id("add_dwell_bin_colors")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_custom_dwell_bins"),
                "col": "visit_bin",
                "new_col": "hex_color",
                "cmap": {
                    "type_": "palette",
                    "name": "RdYlGn",
                },
                "unvisited": "#808080",
            }
            | (params_dict.get("add_dwell_bin_colors") or {}),
            method="call",
        ),
        "persist_dwell_gkpg": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_dwell_gkpg")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_dwell_bin_colors"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename": None,
                "filetypes": [
                    "gpkg",
                ],
                "filename_prefix": "time_spent_per_cell",
                "sanitize": False,
            }
            | (params_dict.get("persist_dwell_gkpg") or {}),
            method="call",
        ),
        "calc_ltd_aoi": Node(
            async_task=calculate_linear_time_density.validate()
            .set_task_instance_id("calc_ltd_aoi")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "percentiles": None,
                "trajectory_gdf": DependsOn("reproject_trajs"),
                "meshgrid": DependsOn("overlay_meshgrid_spatial"),
            }
            | (params_dict.get("calc_ltd_aoi") or {}),
            method="call",
        ),
        "persist_ltd_gkpg": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_ltd_gkpg")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("calc_ltd_aoi"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename": None,
                "filetypes": [
                    "gpkg",
                ],
                "filename_prefix": "patrols_linear_time_density",
                "sanitize": False,
            }
            | (params_dict.get("persist_ltd_gkpg") or {}),
            method="call",
        ),
        "reproject_ltd": Node(
            async_task=reproject_gdf.validate()
            .set_task_instance_id("reproject_ltd")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("calc_ltd_aoi"),
                "target_crs": "EPSG:4326",
            }
            | (params_dict.get("reproject_ltd") or {}),
            method="call",
        ),
        "add_null_ltd_flag": Node(
            async_task=add_non_null_flag.validate()
            .set_task_instance_id("add_null_ltd_flag")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("reproject_ltd"),
                "source_column": "percentile",
                "flag_column": "visited",
            }
            | (params_dict.get("add_null_ltd_flag") or {}),
            method="call",
        ),
        "add_custom_ltd_bins": Node(
            async_task=add_visit_bins.validate()
            .set_task_instance_id("add_custom_ltd_bins")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_null_ltd_flag"),
                "col": "percentile",
                "visited_col": "visited",
                "new_col": "visit_bin",
                "bins": 5,
                "scheme": "natural_breaks",
            }
            | (params_dict.get("add_custom_ltd_bins") or {}),
            method="call",
        ),
        "add_ltd_bin_colors": Node(
            async_task=add_bin_colors.validate()
            .set_task_instance_id("add_ltd_bin_colors")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_custom_ltd_bins"),
                "col": "visit_bin",
                "new_col": "hex_color",
                "cmap": {
                    "type_": "palette",
                    "name": "RdYlGn",
                },
                "unvisited": "#808080",
            }
            | (params_dict.get("add_ltd_bin_colors") or {}),
            method="call",
        ),
        "rename_patrol_cols": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_patrol_cols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "raise_if_not_found": True,
                "df": DependsOn("reproject_trajs"),
                "rename_columns": {
                    "extra__patrol_type__value": "patrol_type",
                    "extra__patrol_serial_number": "patrol_serial_number",
                    "extra__patrol_status": "patrol_status",
                    "extra__patrol_subject": "Name",
                    "extra__subject_id": "ID",
                },
            }
            | (params_dict.get("rename_patrol_cols") or {}),
            method="call",
        ),
        "op_summary_table": Node(
            async_task=operational_days.validate()
            .set_task_instance_id("op_summary_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "trajs": DependsOn("rename_patrol_cols"),
                "segment_start": "segment_start",
                "segment_end": "segment_end",
                "groupby_cols": [
                    "ID",
                    "Name",
                ],
            }
            | (params_dict.get("op_summary_table") or {}),
            method="call",
        ),
        "persist_oper_table": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_oper_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("op_summary_table"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename": None,
                "filetypes": [
                    "csv",
                ],
                "filename_prefix": "patrol_operational_days",
                "sanitize": False,
            }
            | (params_dict.get("persist_oper_table") or {}),
            method="call",
        ),
        "persist_patrol_obs": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_patrol_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_patrol_obs"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename": None,
                "filetypes": [
                    "gpkg",
                ],
                "filename_prefix": "patrol_observations",
                "sanitize": False,
            }
            | (params_dict.get("persist_patrol_obs") or {}),
            method="call",
        ),
        "persist_patrol_trajs": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_patrol_trajs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("patrol_obs_trajs"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename": None,
                "filetypes": [
                    "gpkg",
                ],
                "filename_prefix": "patrol_trajectories",
                "sanitize": False,
            }
            | (params_dict.get("persist_patrol_trajs") or {}),
            method="call",
        ),
        "spatial_features_opacity": Node(
            async_task=set_spatial_features_opacity.validate()
            .set_task_instance_id("spatial_features_opacity")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("select_geo_er"),
                "fill_opacity": 0.0,
                "line_opacity": 1.0,
            }
            | (params_dict.get("spatial_features_opacity") or {}),
            method="call",
        ),
        "spatial_features_layer": Node(
            async_task=create_spatial_features_layer.validate()
            .set_task_instance_id("spatial_features_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("spatial_features_opacity"),
            }
            | (params_dict.get("spatial_features_layer") or {}),
            method="call",
        ),
        "overall_zoom_value": Node(
            async_task=view_state_from_geodataframes.validate()
            .set_task_instance_id("overall_zoom_value")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframes": [
                    DependsOn("select_geo_er"),
                ],
                "max_zoom": 15,
            }
            | (params_dict.get("overall_zoom_value") or {}),
            method="call",
        ),
        "add_time_visit_rgba": Node(
            async_task=hex_column_to_rgba.validate()
            .set_task_instance_id("add_time_visit_rgba")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("reproject_4326"),
                "column": "hex_color",
                "new_column": "rgba_color",
            }
            | (params_dict.get("add_time_visit_rgba") or {}),
            method="call",
        ),
        "order_bin_visit_since": Node(
            async_task=order_bin_categories.validate()
            .set_task_instance_id("order_bin_visit_since")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_time_visit_rgba"),
                "bin_column": "visit_bin",
            }
            | (params_dict.get("order_bin_visit_since") or {}),
            method="call",
        ),
        "create_time_since_layer": Node(
            async_task=create_geojson_layer.validate()
            .set_task_instance_id("create_time_since_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "geodataframe": DependsOn("order_bin_visit_since"),
                "layer_style": {
                    "filled": True,
                    "extruded": False,
                    "stroked": True,
                    "get_fill_color": "rgba_color",
                    "get_line_color": [
                        0,
                        0,
                        0,
                    ],
                    "opacity": 0.65,
                    "get_line_width": 0.35,
                },
                "legend": {
                    "title": "Time Since Visit (Days)",
                    "label_column": "visit_bin",
                    "color_column": "rgba_color",
                    "sort": "ascending",
                    "label_suffix": None,
                },
            }
            | (params_dict.get("create_time_since_layer") or {}),
            method="call",
        ),
        "draw_time_since_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_time_since_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "max_zoom": 10,
                "static": False,
                "title": None,
                "geo_layers": [
                    DependsOn("create_time_since_layer"),
                    DependsOn("spatial_features_layer"),
                ],
                "tile_layers": DependsOn("base_map_defs"),
                "legend_style": {
                    "placement": "bottom-right",
                },
                "view_state": DependsOn("overall_zoom_value"),
            }
            | (params_dict.get("draw_time_since_map") or {}),
            method="call",
        ),
        "time_since_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("time_since_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("draw_time_since_map"),
                "filename": "days_since_patrol_visit_map.html",
            }
            | (params_dict.get("time_since_urls") or {}),
            method="call",
        ),
        "add_dwell_rgba": Node(
            async_task=hex_column_to_rgba.validate()
            .set_task_instance_id("add_dwell_rgba")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_dwell_bin_colors"),
                "column": "hex_color",
                "new_column": "rgba_color",
            }
            | (params_dict.get("add_dwell_rgba") or {}),
            method="call",
        ),
        "order_bin_dwell_since": Node(
            async_task=order_bin_categories.validate()
            .set_task_instance_id("order_bin_dwell_since")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_dwell_rgba"),
                "bin_column": "visit_bin",
            }
            | (params_dict.get("order_bin_dwell_since") or {}),
            method="call",
        ),
        "create_dwell_layer": Node(
            async_task=create_geojson_layer.validate()
            .set_task_instance_id("create_dwell_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "geodataframe": DependsOn("order_bin_dwell_since"),
                "layer_style": {
                    "filled": True,
                    "extruded": False,
                    "stroked": True,
                    "get_fill_color": "rgba_color",
                    "get_line_color": [
                        0,
                        0,
                        0,
                    ],
                    "opacity": 0.65,
                    "get_line_width": 0.35,
                },
                "legend": {
                    "title": "Time Spent(Hours)",
                    "label_column": "visit_bin",
                    "color_column": "rgba_color",
                    "sort": "ascending",
                    "label_suffix": None,
                },
            }
            | (params_dict.get("create_dwell_layer") or {}),
            method="call",
        ),
        "draw_dwell_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_dwell_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "max_zoom": 10,
                "static": False,
                "title": None,
                "geo_layers": [
                    DependsOn("create_dwell_layer"),
                    DependsOn("spatial_features_layer"),
                ],
                "tile_layers": DependsOn("base_map_defs"),
                "legend_style": {
                    "placement": "bottom-right",
                },
                "view_state": DependsOn("overall_zoom_value"),
            }
            | (params_dict.get("draw_dwell_map") or {}),
            method="call",
        ),
        "dwell_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("dwell_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("draw_dwell_map"),
                "filename": "time_spent_per_grid_map.html",
            }
            | (params_dict.get("dwell_urls") or {}),
            method="call",
        ),
        "add_ltd_rgba": Node(
            async_task=hex_column_to_rgba.validate()
            .set_task_instance_id("add_ltd_rgba")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_ltd_bin_colors"),
                "column": "hex_color",
                "new_column": "rgba_color",
            }
            | (params_dict.get("add_ltd_rgba") or {}),
            method="call",
        ),
        "order_bin_ltd_since": Node(
            async_task=order_bin_categories.validate()
            .set_task_instance_id("order_bin_ltd_since")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_ltd_rgba"),
                "bin_column": "visit_bin",
            }
            | (params_dict.get("order_bin_ltd_since") or {}),
            method="call",
        ),
        "create_ltd_layer": Node(
            async_task=create_geojson_layer.validate()
            .set_task_instance_id("create_ltd_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "geodataframe": DependsOn("order_bin_ltd_since"),
                "layer_style": {
                    "filled": True,
                    "extruded": False,
                    "stroked": True,
                    "get_fill_color": "rgba_color",
                    "get_line_color": [
                        0,
                        0,
                        0,
                    ],
                    "opacity": 0.65,
                    "get_line_width": 0.35,
                },
                "legend": {
                    "title": "Time Spent",
                    "label_column": "visit_bin",
                    "color_column": "rgba_color",
                    "sort": "ascending",
                    "label_suffix": None,
                },
            }
            | (params_dict.get("create_ltd_layer") or {}),
            method="call",
        ),
        "draw_ltd_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_ltd_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "max_zoom": 10,
                "static": False,
                "title": None,
                "geo_layers": [
                    DependsOn("create_ltd_layer"),
                    DependsOn("spatial_features_layer"),
                ],
                "tile_layers": DependsOn("base_map_defs"),
                "legend_style": {
                    "placement": "bottom-right",
                },
                "view_state": DependsOn("overall_zoom_value"),
            }
            | (params_dict.get("draw_ltd_map") or {}),
            method="call",
        ),
        "ltd_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("ltd_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("draw_ltd_map"),
                "filename": "ltd_patrols_map.html",
            }
            | (params_dict.get("ltd_urls") or {}),
            method="call",
        ),
        "total_patrols": Node(
            async_task=dataframe_column_nunique.validate()
            .set_task_instance_id("total_patrols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "ID",
                "df": DependsOn("rename_patrol_cols"),
            }
            | (params_dict.get("total_patrols") or {}),
            method="call",
        ),
        "total_patrol_dist": Node(
            async_task=dataframe_column_sum.validate()
            .set_task_instance_id("total_patrol_dist")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "dist_meters",
                "df": DependsOn("rename_patrol_cols"),
            }
            | (params_dict.get("total_patrol_dist") or {}),
            method="call",
        ),
        "total_patrol_dist_converted": Node(
            async_task=with_unit.validate()
            .set_task_instance_id("total_patrol_dist_converted")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "original_unit": "m",
                "new_unit": "km",
                "value": DependsOn("total_patrol_dist"),
            }
            | (params_dict.get("total_patrol_dist_converted") or {}),
            method="call",
        ),
        "patrol_effort_spatial": Node(
            async_task=compute_patrol_effort_fraction.validate()
            .set_task_instance_id("patrol_effort_spatial")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("add_visit_bin_colors"),
            }
            | (params_dict.get("patrol_effort_spatial") or {}),
            method="call",
        ),
        "total_patrols_sv_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_patrols_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Patrols",
                "decimal_places": 0,
                "data": DependsOn("total_patrols"),
            }
            | (params_dict.get("total_patrols_sv_widget") or {}),
            method="call",
        ),
        "total_patrol_dist_sv_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_patrol_dist_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Patrol Distance",
                "decimal_places": 1,
                "data": DependsOn("total_patrol_dist_converted"),
            }
            | (params_dict.get("total_patrol_dist_sv_widget") or {}),
            method="call",
        ),
        "patrol_effort_quantity": Node(
            async_task=to_quantity.validate()
            .set_task_instance_id("patrol_effort_quantity")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "value": DependsOn("patrol_effort_spatial"),
                "unit": "%",
            }
            | (params_dict.get("patrol_effort_quantity") or {}),
            method="call",
        ),
        "patrol_effort_sv_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("patrol_effort_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Patrol Coverage",
                "decimal_places": 1,
                "data": DependsOn("patrol_effort_quantity"),
            }
            | (params_dict.get("patrol_effort_sv_widget") or {}),
            method="call",
        ),
        "time_since_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("time_since_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Days Since Patrol Visit",
                "data": DependsOn("time_since_urls"),
            }
            | (params_dict.get("time_since_map_widget") or {}),
            method="call",
        ),
        "dwell_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("dwell_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Time Spent Per Grid Cell (Hours)",
                "data": DependsOn("dwell_urls"),
            }
            | (params_dict.get("dwell_map_widget") or {}),
            method="call",
        ),
        "ltd_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("ltd_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Patrol Linear Time Density",
                "data": DependsOn("ltd_urls"),
            }
            | (params_dict.get("ltd_map_widget") or {}),
            method="call",
        ),
        "op_summary_table_html": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("op_summary_table_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("op_summary_table"),
                "columns": None,
                "table_config": {
                    "enable_sorting": True,
                    "enable_filtering": True,
                    "enable_download": False,
                    "hide_header": False,
                },
                "widget_id": "Operational Days Summary",
            }
            | (params_dict.get("op_summary_table_html") or {}),
            method="call",
        ),
        "op_summary_table_html_url": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("op_summary_table_html_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "op_summary_table",
                "text": DependsOn("op_summary_table_html"),
            }
            | (params_dict.get("op_summary_table_html_url") or {}),
            method="call",
        ),
        "op_summary_table_widget": Node(
            async_task=create_table_widget_single_view.validate()
            .set_task_instance_id("op_summary_table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Operational Days Summary",
                "data": DependsOn("op_summary_table_html_url"),
            }
            | (params_dict.get("op_summary_table_widget") or {}),
            method="call",
        ),
        "patrol_effort_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("patrol_effort_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("total_patrols_sv_widget"),
                    DependsOn("total_patrol_dist_sv_widget"),
                    DependsOn("patrol_effort_sv_widget"),
                    DependsOn("time_since_map_widget"),
                    DependsOn("dwell_map_widget"),
                    DependsOn("ltd_map_widget"),
                    DependsOn("op_summary_table_widget"),
                ],
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("patrol_effort_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
